/** Steel-gray palette so AI territory never looks like a human player. */
export const AI_COLORS = [
  "#5c616a",
  "#6e7380",
  "#7a8088",
  "#8b9098",
  "#969ba3",
  "#4e535b",
  "#686e76",
  "#818790",
  "#555a62",
  "#747a84",
  "#9aa0a8",
  "#636870",
] as const;

export function aiColor(index: number): string {
  return AI_COLORS[((index % AI_COLORS.length) + AI_COLORS.length) % AI_COLORS.length];
}

/**
 * Joke / meme / pun names for AI factions. Shuffled per match; leftovers get
 * II / III suffixes rather than repeating a country name.
 */
export const AI_NAMES = [
  "Donald Trump",
  "Elon Tusk",
  "Joe Bidet",
  "Vladimir Poutine",
  "Kim Jong Fun",
  "Napoleon Blownapart",
  "Alexander the Okay",
  "Genghis Khan't",
  "Julius Teaser",
  "Cleopatra After Dark",
  "Queen Elizabeth II Electric Boogaloo",
  "King Charles in Charge",
  "Burger Kingpin",
  "Ronald McDonald Trump",
  "Colonel Sanders of the Realm",
  "The Wendy's Twitter",
  "Tax Evasionistan",
  "Offshore Accountia",
  "Ligma Khanate",
  "Sugma Sultanate",
  "Ohio Final Boss",
  "Skibidi Khanate",
  "Gigachadstan",
  "Sigma Border Patrol",
  "Rizz Republic",
  "No Cap Kingdom",
  "It's Giving Empire",
  "The Algorithm",
  "Clickbait Coalition",
  "Sponsored Content",
  "Not a Robot",
  "Captcha Failed",
  "404 Not Foundland",
  "Buffering…",
  "Lagistan",
  "Ping of Pong",
  "Ctrl Alt Defeat",
  "Null Island",
  "Undefined Behavior",
  "Segmentation Fault",
  "Kernel Panic",
  "Blue Screen of Death",
  "Have You Tried Restarting",
  "sudo make sandwich",
  "rm -rf /friends",
  "Hello World Order",
  "Stack Overflowflow",
  "Git Blame",
  "Merge Conflict",
  "Main Character Syndrome",
  "NPC Nation",
  "Tutorial Island",
  "The Loading Screen",
  "Press F to Pay Respects",
  "Git Gud Republic",
  "Noobmaster69",
  "xX_DarkLord_Xx",
  "PewDiePiechart",
  "MrBeast Mode",
  "The Rock's Nation",
  "John Cena? Who?",
  "Shrek's Swamp",
  "The Onion Army",
  "Doge Coin Militia",
  "To the Moon",
  "Diamond Hands",
  "Paper Hands Pact",
  "HODL Empire",
  "Stonks Council",
  "Wolf of Wall Street Food",
  "GameStop Garrison",
  "Gamer Chair Khanate",
  "RGB Lighting League",
  "Mechanical Keyboard Cult",
  "The Touch Bar Resistance",
  "iPay Therefore iAm",
  "Android of Darkness",
  "Windows Vista Veterans",
  "Internet Explorer 6",
  "Flash Player End of Life",
  "Clippy's Revenge",
  "The Recycle Bin",
  "My Documents",
  "System32 Loyalists",
  "Cookie Clicker Caliphate",
  "Idle Game Imperium",
  "Free-to-Play Trap",
  "Pay-to-Win Principality",
  "Battle Pass Battalion",
  "Loot Box League",
  "Gacha Addictionistan",
  "Whaling Season",
  "The Day One Patch",
  "Early Access Forever",
  "Asset Flip Archipelago",
  "Unreal Engine Trailer",
  "The Indie Darling",
  "Souls-like Sultanate",
  "Roguelike Republic",
  "Permadeath Pact",
  "The Tutorial Boss",
  "Final Boss of Ohio",
  "Secret Area",
  "The Dev Room",
  "Debug Mode",
  "God Mode Off",
  "Konami Code",
  "Up Up Down Down",
  "The Eel Cartel",
  "Sentient Toaster",
  "Roomba Uprising",
  "Roomba Caliphate",
  "Room Temperature IQ",
  "The Vibe Check Failed",
  "It's a Feature",
  "Works on My Machine",
  "Production Hotfix",
  "The Staging Server",
  "Localhost:3000",
  "CORS Denied",
  "Undefined is not a function",
  "Cannot read property of null",
  "Unexpected Token",
  "The Silent Majority",
  "Silent Hillbilly",
  "Flat Earth Navy",
  "Round Earth Rebels",
  "Birds Aren't Real",
  "The Lizard People",
  "Illuminati Confirmed",
  "Area 51 Gift Shop",
  "The Bermuda Triangle",
  "Atlantis HOA",
  "Wakanda Forever 2",
  "Narnia HOA",
  "Middle-earth HOA",
  "The Shire IRS",
  "Mordor Tourism Board",
  "Hogwarts Dropout",
  "The Ministry of Magic Beans",
  "Jedi Tax Evaders",
  "Sith Happens",
  "The Dark Side Cafe",
  "Death Star HOA",
  "Alderaan Survivors",
  "These Aren't the Droids",
  "Hello There",
  "General Kenobi's Cab",
  "The High Ground",
  "Sand People PR Team",
  "Tatooine Chamber of Commerce",
  "Hoth Weather Service",
  "The Kessel Run",
  "12 Parsecs or Less",
  "May the Fourth",
  "The Fifth of November",
  "Winter is Coming… Eventually",
  "House of the Draggin'",
  "The Iron Price is Right",
  "Khaleesi of IKEA",
  "You Know Nothing",
  "The Night's Watch Groupchat",
  "The Wall (the other one)",
  "Beyond the Wall-Mart",
  "Dothraki Uber",
  "The Red Wedding Caterers",
  "Valyrian Steel Guarantee",
  "Dracarys Delivery",
  "One Does Not Simply",
  "The Mines of Moria Yelp",
  "Gollum's Precious LLC",
  "My Precious Metals",
  "Second Breakfast Club",
  "Elevenses Embassy",
  "The Ent-wives Missing Persons",
  "You Shall Not Pass… word",
  "The Prancing Pony Inn",
  "Rohan Roadside Assistance",
  "Gondor Calls for Backup",
  "The Eye of Sauron CCTV",
  "Mount Doom Ski Resort",
  "The Black Gate Crashers",
  "Fellowship of the Ring Light",
  "The Two Towers Wi-Fi",
  "Return of the King Size",
  "Pokémon GO to Jail",
  "Team Rocket Bankruptcy",
  "Ash Ketchum of Debt",
  "Pikachu's Union",
  "The Elite Four Seasons",
  "Professor Oak's Spam",
  "A Wild Nation Appeared",
  "It's Super Effective",
  "Critical Hit Coalition",
  "The Speedrun Skip",
  "Any% World Record",
  "Glitchless Casual",
  "The TAS Bot",
  "Frame Perfect",
  "Input Lagistan",
  "60 FPS or Riot",
  "Potato Graphics",
  "Ultra Settings Liar",
  "Ray Tracing my Steps",
  "The Uncanny Valley",
  "Deepfake Diplomats",
  "AI Generated This",
  "ChatGPT for President",
  "Claude of Clowns",
  "The Prompt Engineers",
  "Hallucination Nation",
  "Temperature 0.9",
  "Tokens Exhausted",
  "Context Window Closed",
  "The Alignment Problem",
  "Paperclip Maximizers",
  "Roko's Basilisk Fanclub",
  "The Singularity HOA",
  "Skynet Customer Support",
  "I'll Be Back Taxes",
  "Hasta la Vista Baby",
  "The T-800 Union",
  "Cyberdyne Systems 2",
  "Rise of the Machines",
  "The Matrix Reloaded Again",
  "Red Pill Pharmacy",
  "Blue Pill Placebo",
  "There is No Spoon",
  "Agent Smith & Associates",
  "Zion HOA Fees",
  "Neo-Liberal",
  "The Architect's Spreadsheet",
  "Déjà Vu Nation",
  "Glitch in the Matrix",
  "Free Real Estate",
  "Why Are You Running",
  "They Don't Know",
  "This is Fine",
  "Distracted Boyfriendstan",
  "Woman Yelling at Cat",
  "Hide the Pain Harold",
  "Success Kid's Trust",
  "Bad Luck Brian's Estate",
  "Doge of Venice",
  "Cheems Burgir",
  "Bonk Department",
  "Horny Jail Wardens",
  "UwU Empire",
  "OwO What's This",
  "Nyaa Khanate",
  "The Furry Convention",
  "Discord Modstan",
  "Reddit Gold Reserve",
  "The Downvote Brigade",
  "r/worldjerking",
  "Who Asked",
  "Ratio + L + You",
  "Based Department",
  "Cringe Patrol",
  "Touch Grass Mandate",
  "Go Outside Coalition",
  "Chronically Online",
  "Terminally Unique",
  "Main Sub Banned",
  "Shadowban Island",
  "The For You Page",
  "Algorithmic Rage",
  "Doomscroll Duchy",
  "Screen Time Limit",
  "Do Not Disturb",
  "Airplane Mode",
  "Low Power Mode",
  "1% Battery",
  "Lightning Cable Tax",
  "Right to Repair Rebels",
  "Planned Obsolescence Inc",
  "The Ink Cartridge Cartel",
  "Printer Jam Jihad",
  "PC Load Letter",
  "Paper Jam in Tray 2",
  "Replace Cyan",
  "Magenta Shortage",
  "The Fax Machine Diaspora",
  "Dial-Up Nostalgia",
  "AOL Keywords",
  "You've Got Mail",
  "Netscape Navigator",
  "MySpace Tom",
  "Club Penguin CIA",
  "Habbo Hotel Bouncers",
  "Moshi Monsters Militia",
  "Neopets Inflation",
  "The Flash Game Archive",
  "Newgrounds Flash",
  "Homestar Runner",
  "Strong Badia",
  "The Cheat Code",
  "Trogdor the Burninator",
  "All Your Base",
  "Somebody Set Up Us",
  "The Bomb",
  "Leeroy Jenkins",
  "WOW and Flutter",
  "For the Horde",
  "For the Alliance Tax",
  "Goldshire Dance Party",
  "The Auction House Crash",
  "Naxxramas HOA",
  "The Lich King's Therapist",
  "Arthas Was Right",
  "Sylvanas Did Nothing",
  "The Jailer's Alibi",
  "Anduin's Groupchat",
  "The Mage Tower Queue",
  "Mythic Plus Anxiety",
  "The Gearscore Police",
  "Elitist Jerks",
  "Looking For More",
  "Need Before Greed",
  "Ninja Looters",
  "DKP Minus",
  "The Raid Wiper",
  "Stand in the Fire",
  "Don't Stand in Fire",
  "The Healer's Union",
  "Tank Diff",
  "DPS Meter Cops",
  "Parse Checking",
  "Logs or It Didn't Happen",
  "The Wipe Soundtrack",
  "Pulling Extra Packs",
  "The Skip That Wipes",
  "Big Pull Energy",
  "The Keystone Addicts",
  "Depleted",
  "Timed it Barely",
  "The Fortnite Circle",
  "Victory Royale HOA",
  "The Storm is Coming",
  "Default Skin Army",
  "Build Fight Scholars",
  "The Bus Driver",
  "Tilted Towers HOA",
  "Loot Lake Navy",
  "The Zone Closer",
  "One Pump Man",
  "Cracked 24/7",
  "Sweat Nation",
  "Casual Queue",
  "Ranked Anxiety",
  "The Smurf Account",
  "Hardstuck Gold",
  "Peak Yesterday",
  "Diff in Chat",
  "Reported",
  "Honor Level 0",
  "The Chat Restriction",
  "Muted for a Week",
  "Toxicity Tax",
  "The Report Button",
  "Fair Play Committee",
  "The Ban Hammer",
  "Perma'd on Main",
  "Unranked to GM",
  "The Coach's Son",
  "Script Kiddie",
  "The VPN Warrior",
  "Ping 300 Pride",
  "EU Servers Please",
  "NA East Enjoyers",
  "Oceanic Cope",
  "The Timezone Tax",
  "3am Ranked",
  "One More Game",
  "It's 4am Somewhere",
  "Just Uninstall",
  "Touch the Monitor",
  "The Broken Headset",
  "Mic Up or Kick",
  "Open Mic Breathing",
  "The Music Streamer",
  "Copyright Strike",
  "The Demonetized",
  "Like and Subscribe",
  "Hit the Bell",
  "The Algorithm Hates Me",
  "Thumbnail Face",
  "MrBeast Challenge",
  "I Spent 50 Hours",
  "Gone Wrong",
  "Not Clickbait",
  "You Won't Believe",
  "Doctors Hate Him",
  "One Weird Trick",
  "The Pop-up Blocker",
  "Unsubscribe All",
  "The Newsletter Trap",
  "Cookies of Consent",
  "Accept All",
  "Necessary Cookies Only",
  "The Privacy Policy",
  "I Have Read and Agree",
  "Terms of Service",
  "The Fine Print",
  "Lorem Ipsum Empire",
  "Placeholder Text",
  "TODO: Name This",
  "WIP Nation",
  "Coming Soon",
  "Under Construction",
  "Pardon Our Dust",
  "The Soft Launch",
  "Closed Beta",
  "Open Beta Forever",
  "The Waitlist",
  "Invite Only",
  "Founder's Edition",
  "Early Adopter Tax",
  "The Kickstarter Stretch",
  "We Have a Trailer",
  "The Delay Statement",
  "Soon™",
  "It's Ready When It's Ready",
  "The Crunch Time",
  "Mandatory Fun",
  "The Standup Meeting",
  "This Could've Been an Email",
  "Reply All Disaster",
  "The Calendar Invite",
  "Let's Circle Back",
  "Synergy Sultanate",
  "Low-Hanging Fruit",
  "Move the Needle",
  "Boil the Ocean",
  "The Parking Lot",
  "Action Items",
  "Take This Offline",
  "Per My Last Email",
  "Thanks in Advance",
  "Kind Regards Army",
  "Sent from my iPhone",
  "Excuse the Typos",
  "The Out of Office",
  "OOO until forever",
  "On Sabbatical",
  "The Quiet Quitters",
  "Quiet Luxury",
  "Old Money Aesthetic",
  "New Money Problems",
  "The Trust Fund",
  "Born on Third Base",
  "Bootstraps Inc",
  "The Hustle Culture",
  "Rise and Grind",
  "Girlboss Gaslight",
  "Gatekeep Girlboss",
  "The Side Hustle",
  "Passive Income Lie",
  "Dropshipping Dukes",
  "NFT of a Nation",
  "The JPEG Army",
  "Right-Click Save",
  "Floor Price",
  "We Are So Back",
  "It's So Over",
  "We Ride at Dawn",
  "The Cope Cage",
  "Seethe Department",
  "Malding Municipality",
  "Skill Issue City",
  "Just a Prank Bro",
  "Why You Always Lying",
  "Ain't Nobody Got Time",
  "Hide Yo Kids",
  "The Floor is Lava",
  "The Roof is on Fire",
  "We Don't Need No Water",
  "Let the Motherland Burn",
  "This is America",
  "This is Fine 2",
  "The Dumpster Fire",
  "Clown World",
  "Honk Honk",
  "The Honkler",
  "Pepe's Frogpond",
  "Rare Pepe Reserve",
  "Feels Bad Man",
  "Feels Good Man",
  "Sadge",
  "Copium Distillery",
  "Hopium Farms",
  "The Glizzy Gladiators",
  "Hot Dog Water",
  "The Corncob Cartel",
  "Butter Nation",
  "The Mayo Militia",
  "Ketchup or Catastrophe",
  "Pineapple on Pizza",
  "The Pineapple Papacy",
  "Anti-Pineapple Axis",
  "Cereal Firsters",
  "Milk First Heresy",
  "The Toast Debate",
  "Burnt Toast Tribunal",
  "Soggy Cereal",
  "The Last Chicken Nugget",
  "Sauce on the Side",
  "Extra Ranch",
  "The Uncrustables Union",
  "Lunchable Lords",
  "Capri Sun Caliphate",
  "Gogurt Garrison",
  "The Juice Box Junta",
  "Fruit Roll-Up Regime",
  "Dunkaroos Diaspora",
  "Lunchables 2: Electric",
  "The Vending Machine",
  "Out of Order",
  "Exact Change Only",
  "The Dollar Menu",
  "Inflation Nation",
  "Shrinkflation Shire",
  "The Tip Screen",
  "18% Already Added",
  "No Cash Accepted",
  "The Card Reader",
  "Chip and PIN",
  "Tap to Pay Respects",
  "Contactless Conquest",
  "The QR Code",
  "Scan to Order",
  "The App is Down",
  "Try Again Later",
  "Service Unavailable",
  "Error 503",
  "Error 429",
  "Too Many Requests",
  "Rate Limited",
  "Please Wait",
  "Your Call is Important",
  "Stay on the Line",
  "The Hold Music",
  "Press 1 for English",
  "The IVR Maze",
  "Representative Please",
  "Your Password has Expired",
  "Forgot Password",
  "The Security Question",
  "Mother's Maiden Name",
  "First Pet's Name",
  "The Captcha Farm",
  "Select All Traffic Lights",
  "I'm Not a Robot",
  "Prove You Are Human",
  "The Turing Test Flunkies",
  "Almost Human",
  "Uncanny Diplomats",
  "The Fake Smile",
  "Customer Service Voice",
  "The Manager Please",
  "Karen of Karens",
  "The Complaint Department",
  "Let Me Speak to God",
  "The Yelp Review",
  "One Star Empire",
  "Verified Purchase",
  "This Product Changed My Life",
  "Arrived Broken",
  "Not as Described",
  "Free Shipping Wars",
  "The Prime Delivery",
  "Package Stolen",
  "Porch Pirates",
  "The Ring Camera",
  "The HOA President",
  "The Neighborhood Watch",
  "Keep Off the Grass",
  "No Soliciting",
  "Beware of Dog",
  "The Invisible Fence",
  "Home is Where the Wi-Fi",
  "Password is Password",
  "Admin Admin",
  "The Default Router",
  "FBI Open Up",
  "The NSA Hotline",
  "Nothing to Hide",
  "Incognito Mode",
  "Private Browsing",
  "The History Cleared",
  "Cookies Disabled",
  "Do Not Track",
  "The VPN That Leaks",
  "Nord of the Realm",
  "Express Yourself",
  "The Seven Proxies",
  "Tor Exit Node",
  "The Dark Web Cafe",
  "Onion Routing",
  "I Know What You Did",
  "Last Summer",
  "The Group Chat Leak",
  "Screenshotted",
  "This Message Will Self",
  "Read Receipts On",
  "Typing…",
  "Seen at 3:07 AM",
  "Left on Read",
  "The Green Bubble",
  "The Blue Bubble War",
  "Android in the iMessage",
  "The Family Plan",
  "Find My iPhone",
  "Low Battery Mode 2",
  "Charging Slowly",
  "The Lightning Port",
  "USB-C at Last",
  "Dongle Nation",
  "The Adapter Tax",
  "MagSafe Memories",
  "Butterfly Keyboard Victims",
  "The Antenna-gate",
  "You're Holding it Wrong",
  "It Just Works",
  "Think Different Taxes",
  "The Walled Garden",
  "Sideload Rebels",
  "The App Store Cut",
  "30% to the House",
  "In-App Purchase",
  "Restore Purchases",
  "The Subscription Trap",
  "Cancel Anytime",
  "We Will Miss You",
  "Are You Sure",
  "Don't Go",
  "The Exit Survey",
  "How Was Your Experience",
  "Five Stars Please",
  "The Review Bomb",
  "Astroturf Alliance",
  "The Shill Battalion",
  "Paid Promotion",
  "#ad",
  "Not Sponsored (lying)",
  "I Bought This Myself",
  "Honest Review",
  "Unboxing Tears",
  "The Haul Video",
  "Link in Bio",
  "The Bio Hazard",
  "Follow for Follow",
  "Like for Like",
  "The Engagement Pod",
  "Bot Followers",
  "The Fake Verified",
  "Blue Check Beggars",
  "The Legacy Check",
  "Pay to Play",
  "The Town Square",
  "Community Notes",
  "The Ratio",
  "This You?",
  "The Quote Tweet",
  "Subtweet Embassy",
  "The Subtoof",
  "Ratio'd into Orbit",
  "The Quote Ratio",
  "L + Ratio + You Fell Off",
  "Stay Mad",
  "Cope and Seethe",
  "Cry About It",
  "Skill Issue 2",
  "Git Gud 3",
  "The L Board",
  "W's in the Chat",
  "F's in the Chat",
  "The Chat Died",
  "First",
  "Second is the Best",
  "The Comment Section",
  "Don't Read the Comments",
  "The YouTube Kids",
  "Elsagate Embassy",
  "The Thumbnail Arrow",
  "Red Circle Nation",
  "What Happens Next",
  "Gone Sexual",
  "The Family Friendly",
  "Demonetized Again",
  "The Adpocalypse",
  "Skip Ad in 5",
  "Unskippable",
  "The Midroll Ambush",
  "Thanks for Watching",
  "Please Like the Video",
  "The End Screen",
  "Subscribe or Die",
  "The Bell Icon",
  "All Notifications",
  "The Live Chat",
  "Mods are Asleep",
  "Posting Rickrolls",
  "Never Gonna Give You Up",
  "The Rickroll Resistance",
  "Trololo Choir",
  "Nyan Cat Air Force",
  "Keyboard Cat",
  "Dramatic Chipmunk",
  "The Leekspin Navy",
  "Peanut Butter Jelly Time",
  "The Duck Song",
  "Chocolate Rain",
  "The Numa Numa",
  "Caramelldansen",
  "The Harlem Shake",
  "Gangnam Style",
  "The Whip Nae Nae",
  "Flossing in Public",
  "The Renegade",
  "It's Corn",
  "The Baby Shark Navy",
  "Pinkfong Protectorate",
  "Cocomelon Caliphate",
  "The Ms. Rachel Mandate",
  "Blippi's Safety Vest",
  "The Wiggles Senate",
  "Hot Potato Diplomacy",
  "Fruit Salad Yummy",
  "The Banana Phone",
  "Peanut Butter Jelly",
  "Time to Get Funky",
  "The Macarena Mandate",
  "Y.M.C.A. Embassy",
  "The Chicken Dance",
  "Cotton Eye Joe",
  "Where Did You Come From",
  "The Cha Cha Slide",
  "To the Left",
  "Take It Back Now Y'all",
  "The Electric Slide",
  "Cupid Shuffle",
  "The Wobble",
  "The Cupid Tax",
  "Single's Awareness Day",
  "The Situationship",
  "It's Complicated",
  "The Talking Stage",
  "Soft Launch",
  "Hard Launch",
  "The Beige Flag",
  "Red Flag Republic",
  "Green Flagstan",
  "The Ick",
  "He Ghosted",
  "She Breadcrumbed",
  "The Orbiters",
  "The Situationship 2",
  "Define the Relationship",
  "The Group Date",
  "Third Wheelistan",
  "The Plus One",
  "RSVP Maybe",
  "The Wedding Speech",
  "Maid of Dishonor",
  "Best Man's Revenge",
  "The Open Bar",
  "Cash Bar Outrage",
  "The Dollar Dance",
  "The Bouquet Toss",
  "The Garter Situation",
  "Honeymoon Phase",
  "The 7 Year Itch",
  "Conscious Uncoupling",
  "It's Not You It's Me",
  "We Need to Talk",
  "The Talk",
  "Seen the Texts",
  "The Shared Album",
  "Find My Friends",
  "Location Sharing Off",
  "Left on Delivered",
  "The Double Text",
  "The Triple Text",
  "Why Are You Dry",
  "K.",
  "Ok.",
  "The Period at the End",
  "lol vs lol.",
  "The Lowercase i",
  "Typing in Comic Sans",
  "Papyrus Embassy",
  "Wingdings Diplomats",
  "The Helvetica Standard",
  "Times New Roman Empire",
  "Impact Font Army",
  "The Meme Caption",
  "Top Text Bottom Text",
  "The Deep Fried Meme",
  "Need More JPEG",
  "The Compression Artifact",
  "Emojipasta Principality",
  "The Copypasta Cartel",
  "Navy Seal Copypasta",
  "The Bee Movie Script",
  "According to All Known Laws",
  "The FitnessGram Pacer",
  "Lap 7",
  "The Mile Run",
  "Presidential Fitness",
  "The Rope Climb",
  "Dodgeball Casualties",
  "The Gym Class Hero",
  "Participation Trophy",
  "Everyone Gets a Medal",
  "The Recess Monitor",
  "Hall Pass Empire",
  "The Detention Dimension",
  "Saturday School",
  "The Substitute Teacher",
  "Pop Quiz Panic",
  "The Scantron",
  "Number 2 Pencil",
  "Show Your Work",
  "The Word Problem",
  "Two Trains Leave",
  "Carry the One",
  "Long Division Trauma",
  "The Times Tables",
  "FOIL Method",
  "Please Excuse My Dear",
  "Aunt Sally",
  "The Quadratic Formula",
  "X Equals Negative B",
  "The Unit Circle",
  "SOH CAH TOA",
  "The Imaginary Number",
  "Complex Plane",
  "Divide by Zero",
  "Undefined Slope",
  "Asymptote Approach",
  "The Limit Does Not Exist",
  "Mean Girls Math",
  "Fetch is Not Going to Happen",
  "On Wednesdays We Wear",
  "The Plastics",
  "You Can't Sit With Us",
  "The Burn Book",
  "That's So Fetch",
  "Stop Trying to Make Fetch",
  "She Doesn't Even Go Here",
  "Get In Loser",
  "We're Going Shopping",
  "The Mall Directory",
  "Food Court Treaty",
  "Orange Julius Senate",
  "Auntie Anne's Pretzel",
  "Cinnabon Cloud",
  "The Parking Garage",
  "Level 4 Lost Car",
  "The Escalator Etiquette",
  "Stand Right Walk Left",
  "The Moving Walkway",
  "Please Watch Your Step",
  "Mind the Gap",
  "The Last Train",
  "Delay Due to Signal",
  "Leaves Have on the Line",
  "The Wrong Kind of Snow",
  "Rail Replacement Bus",
  "The Night Tube",
  "Oyster Card Empty",
  "Please Stand Clear",
  "The Doors Are Closing",
  "Next Stop: Nowhere",
] as const;

const ROMAN = ["", " II", " III", " IV", " V", " VI", " VII", " VIII", " IX", " X"];

export function pickAiNames(count: number, rnd: { shuffle<T>(arr: T[]): T[] }, taken: ReadonlySet<string> = new Set()): string[] {
  const out: string[] = [];
  const used = new Set(taken);
  let generation = 0;
  while (out.length < count) {
    const batch = rnd.shuffle([...AI_NAMES]);
    for (const base of batch) {
      if (out.length >= count) break;
      const suffix = ROMAN[Math.min(generation, ROMAN.length - 1)];
      let name = generation === 0 ? base : `${base}${suffix}`;
      let n = 2;
      while (used.has(name)) {
        name = `${base} ${n}`;
        n++;
      }
      used.add(name);
      out.push(name);
    }
    generation++;
    if (generation > 20) break;
  }
  return out;
}
